/*
 *   SfuncApplyFILT_1stOrderLagIfEnbld_usp.c Simple C-MEX S-function for function call.
 *
 *   ABSTRACT:
 *     The purpose of this sfunction is to call a simple legacy
 *     function during simulation:
 *
 *        single y1 = ApplyFILT_1stOrderLagIfEnbld_usp(single u1, single u2, single u3)
 *
 *   Simulink version           : 7.7 (R2011a) 09-Mar-2011
 *   C source code generated on : 31-Oct-2013 12:12:07

 * THIS S-FUNCTION IS GENERATED BY THE LEGACY CODE TOOL AND MAY NOT WORK IF MODIFIED

 */

/*
   %%%-MATLAB_Construction_Commands_Start
   def = legacy_code('initialize');
   def.SFunctionName = 'SfuncApplyFILT_1stOrderLagIfEnbld_usp';
   def.OutputFcnSpec = 'single y1 = ApplyFILT_1stOrderLagIfEnbld_usp(single u1, single u2, single u3)';
   def.HeaderFiles = {'ApplyFILT_1stOrderLagIfEnbld_usp.h'};
   def.SourceFiles = {'ApplyFILT_1stOrderLagIfEnbld_usp.c'};
   legacy_code('sfcn_cmex_generate', def);
   legacy_code('compile', def);
   %%%-MATLAB_Construction_Commands_End
 */

/*
 * Must specify the S_FUNCTION_NAME as the name of the S-function.
 */
#define S_FUNCTION_NAME                SfuncApplyFILT_1stOrderLagIfEnbld_usp
#define S_FUNCTION_LEVEL               2

/*
 * Need to include simstruc.h for the definition of the SimStruct and
 * its associated macro definitions.
 */
#include "simstruc.h"


/* define error messages */
#define ERR_INVALID_SET_INPUT_DTYPE_CALL  \
              "Invalid call to mdlSetInputPortDataType"

#define ERR_INVALID_SET_OUTPUT_DTYPE_CALL \
              "Invalid call to mdlSetOutputPortDataType"

#define ERR_INVALID_DTYPE     "Invalid input or output port data type"

#define TRUE 1
        
#define FALSE 0

/*
 * Specific header file(s) required by the legacy code function.
 */
#include "ApplyFILT_1stOrderLagIfEnbld_usp.h"

/* Function: mdlInitializeSizes ===========================================
 * Abstract:
 *    The sizes information is used by Simulink to determine the S-function
 *    block's characteristics (number of inputs, outputs, states, etc.).
 */
static void mdlInitializeSizes(SimStruct *S)
{
  /* Number of expected parameters */
  ssSetNumSFcnParams(S, 0);

  /*
   * Set the number of pworks.
   */
  ssSetNumPWork(S, 0);

  /*
   * Set the number of dworks.
   */
  if (!ssSetNumDWork(S, 0))
    return;

  /*
   * Set the number of input ports.
   */
  if (!ssSetNumInputPorts(S, 3))
    return;

  /*
   * Configure the input port 1
   */
  ssSetInputPortDataType(S, 0, DYNAMICALLY_TYPED);
  ssSetInputPortWidth(S, 0, DYNAMICALLY_SIZED);
  ssSetInputPortDirectFeedThrough(S, 0, 1);

  /*
   * Configure the input port 2
   */
  ssSetInputPortDataType(S, 1, DYNAMICALLY_TYPED);
  ssSetInputPortWidth(S, 1, DYNAMICALLY_SIZED);
  ssSetInputPortDirectFeedThrough(S, 1, 1);

  /*
   * Configure the input port 3
   */
  ssSetInputPortDataType(S, 2, DYNAMICALLY_TYPED);
  ssSetInputPortWidth(S, 2, DYNAMICALLY_SIZED);
  ssSetInputPortDirectFeedThrough(S, 2, 1);

  /*
   * Set the number of output ports.
   */
  if (!ssSetNumOutputPorts(S, 1))
    return;

  /*
   * Configure the output port 1
   */
  ssSetOutputPortDataType(S, 0, DYNAMICALLY_TYPED);
  ssSetOutputPortWidth(S, 0, 1);

  /*
   * Register reserved identifiers to avoid name conflict
   */
  if (ssRTWGenIsCodeGen(S)) {
    /*
     * Register reserved identifier for OutputFcnSpec
     */
    ssRegMdlInfo(S, "ApplyFILT_1stOrderLagIfEnbld_usp", MDL_INFO_ID_RESERVED, 0,
                 0, ssGetPath(S));
  }

  /*
   * This S-function can be used in referenced model simulating in normal mode.
   */
  ssSetModelReferenceNormalModeSupport(S, MDL_START_AND_MDL_PROCESS_PARAMS_OK);

  /*
   * Set the number of sample time.
   */
  ssSetNumSampleTimes(S, 1);

  /*
   * All options have the form SS_OPTION_<name> and are documented in
   * matlabroot/simulink/include/simstruc.h. The options should be
   * bitwise or'd together as in
   *   ssSetOptions(S, (SS_OPTION_name1 | SS_OPTION_name2))
   */
  ssSetOptions(S,
               SS_OPTION_USE_TLC_WITH_ACCELERATOR |
               SS_OPTION_CAN_BE_CALLED_CONDITIONALLY |
               SS_OPTION_EXCEPTION_FREE_CODE |
               SS_OPTION_WORKS_WITH_CODE_REUSE |
               SS_OPTION_SFUNCTION_INLINED_FOR_RTW |
               SS_OPTION_DISALLOW_CONSTANT_SAMPLE_TIME);
}

/* Function: mdlInitializeSampleTimes =====================================
 * Abstract:
 *    This function is used to specify the sample time(s) for your
 *    S-function. You must register the same number of sample times as
 *    specified in ssSetNumSampleTimes.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
  ssSetSampleTime(S, 0, INHERITED_SAMPLE_TIME);
  ssSetOffsetTime(S, 0, FIXED_IN_MINOR_STEP_OFFSET);

#if defined(ssSetModelReferenceSampleTimeDefaultInheritance)

  ssSetModelReferenceSampleTimeDefaultInheritance(S);

#endif

}

/* Function: mdlOutputs ===================================================
 * Abstract:
 *    In this function, you compute the outputs of your S-function
 *    block. Generally outputs are placed in the output vector(s),
 *    ssGetOutputPortSignal.
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
  /*
   * Get access to Parameter/Input/Output/DWork/size information
   */
   
   InputPtrsType u0ptrs = ssGetInputPortSignalPtrs(S,0);
   InputPtrsType u1ptrs = ssGetInputPortSignalPtrs(S,1);
   InputPtrsType u2ptrs = ssGetInputPortSignalPtrs(S,2); 
 
    DTypeId   y0DataType = ssGetInputPortDataType(S, 1);
	
	    switch(y0DataType)
    {
        case SS_UINT16:
        {
	
  // uint16_T *u11 = (uint16_T *) ssGetInputPortSignalPtrs(S, 0);
  // uint16_T *u12 = (uint16_T *) ssGetInputPortSignalPtrs(S, 1);
  // uint16_T *u13 = (uint16_T *) ssGetInputPortSignalPtrs(S, 2);
  
			uint16_T *y1 = (uint16_T *) ssGetOutputPortSignal(S, 0);
  			InputUInt16PtrsType  u11  = (InputUInt16PtrsType)u0ptrs;
			InputUInt16PtrsType  u12  = (InputUInt16PtrsType)u1ptrs;
			InputUInt16PtrsType  u13  = (InputUInt16PtrsType)u2ptrs;

  /*
   * Call the legacy code function
   */
//  *y1 = ApplyFILT_1stOrderLagIfEnbld_usp_fixed( *u1, *u2, *u3);

  if ( *u13[0] >= 65535 )
  {
    y1[0] = *u12[0];
  }
  else
  {
    y1[0] = ApplyFILT_1stOrderLag_usp_fixed( *u11[0], *u12[0], *u13[0] );
  }

				break;
         }
        case SS_SINGLE:
        {
		
  // real32_T *u1 = (real32_T *) ssGetInputPortSignal(S, 0);
  // real32_T *u2 = (real32_T *) ssGetInputPortSignal(S, 1);
  // real32_T *u3 = (real32_T *) ssGetInputPortSignal(S, 2);
  // real32_T *y1 = (real32_T *) ssGetOutputPortSignal(S, 0);

			real32_T *y1 = (real32_T *) ssGetOutputPortSignal(S, 0);
  			InputReal32PtrsType  u21  = (InputReal32PtrsType)u0ptrs;
			InputReal32PtrsType  u22  = (InputReal32PtrsType)u1ptrs;
			InputReal32PtrsType  u23  = (InputReal32PtrsType)u2ptrs;

  /*
   * Call the legacy code function
   */
//  *y1 = ApplyFILT_1stOrderLagIfEnbld_usp_fixed( *u1, *u2, *u3);

  if ( *u23[0] >= 1.0 )
  {
    y1[0] = *u22[0];
  }
  else
  {
    y1[0] = ApplyFILT_1stOrderLag_usp( *u21[0], *u22[0], *u23[0] );
  }
		
			break;
         }
    }
	
}

/* Function: mdlTerminate =================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.
 */
static void mdlTerminate(SimStruct *S)
{
}



#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */

#define MDL_SET_INPUT_PORT_DATA_TYPE

/* Function: mdlSetInputPortDataType ==========================================
 *    This routine is called with the candidate data type for a dynamically
 *    typed port.  If the proposed data type is acceptable, the routine should
 *    go ahead and set the actual port data type using ssSetInputPortDataType.
 *    If the data type is unacceptable an error should generated via
 *    ssSetErrorStatus.  Note that any other dynamically typed input or
 *    output ports whose data types are implicitly defined by virtue of knowing
 *    the data type of the given port can also have their data types set via 
 *    calls to ssSetInputPortDataType or ssSetOutputPortDataType.
 */
static void mdlSetInputPortDataType(SimStruct *S, 
                                    int       port, 
                                    DTypeId   dataType)
{
    if( ( port == 0 ) ) {
            /*
             * Accept proposed data type if it is an unsigned integer type
             * force all data ports to use this data type.
             */
            ssSetInputPortDataType(  S, 0, dataType );
       
    }else if(port == 1) {

                ssSetInputPortDataType(  S, 1, dataType );
    }else if(port == 2) {

                ssSetInputPortDataType(  S, 2, dataType );
    }
    else {
        /* 
         * Should not end up here.  Simulink will only call this function
         * for existing input ports whose data types are unknown.
         */
        ssSetErrorStatus(S, ERR_INVALID_SET_INPUT_DTYPE_CALL);
        goto EXIT_POINT;
    }

EXIT_POINT:
    return;
} /* mdlSetInputPortDataType */



#define MDL_SET_OUTPUT_PORT_DATA_TYPE
/* Function: mdlSetOutputPortDataType =========================================
 *    This routine is called with the candidate data type for a dynamically
 *    typed port.  If the proposed data type is acceptable, the routine should
 *    go ahead and set the actual port data type using ssSetOutputPortDataType.
 *    If the data tyoe is unacceptable an error should generated via
 *    ssSetErrorStatus.  Note that any other dynamically typed input or
 *    output ports whose data types are implicitly defined by virtue of knowing
 *    the data type of the given port can also have their data types set via 
 *    calls to ssSetInputPortDataType or ssSetOutputPortDataType.
 */
static void mdlSetOutputPortDataType(SimStruct *S, 
                                     int       port, 
                                     DTypeId   dataType)
{
    if ( port == 0 ) {
            /*
             * Accept proposed data type if it is an unsigned integer type
             * force all the ports to use this data type.
             */
           ssSetOutputPortDataType( S, 0, dataType );            
    }
    else {
        /* 
         * Should not end up here.  Simulink will only call this function
         * for existing output ports whose data types are unknown.  
         */
        ssSetErrorStatus(S, ERR_INVALID_SET_OUTPUT_DTYPE_CALL);
        goto EXIT_POINT;
    }

EXIT_POINT:
    return;

} /* mdlSetOutputPortDataType */


#define MDL_SET_DEFAULT_PORT_DATA_TYPES
/* Function: mdlSetDefaultPortDataTypes ========================================
 *    This routine is called when Simulink is not able to find data type 
 *    candidates for dynamically typed ports. This function must set the data 
 *    type of all dynamically typed ports.
 */
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    /* Set input port data type to uint8 */
    // ssSetInputPortDataType(  S, 0, SS_INT32 );            
    // ssSetInputPortDataType(  S, 1, SS_INT32 );
    // ssSetInputPortDataType(  S, 2, SS_UINT8 );
       ssSetOutputPortDataType( S, 0, SS_UINT16 );
} /* mdlSetDefaultPortDataTypes */
#endif

/*
 * Required S-function trailer
 */
#ifdef MATLAB_MEX_FILE
# include "simulink.c"
#else
# include "cg_sfun.h"
#endif
